--- 
document: 
  name: "Framework per le competenze digitali della Commissione Europea (DigComp)"
  description: |
     Traduzione in italiano su Docs Italia del framework per le competenze digitali della Commissione Europea (DigComp) 
  tags:
    - competenze digitali
